#!/bin/sh

usage() {
    echo "Usage: litevirt-creator [OPTION]..."
    echo "Create a litevirt hypervisor livecd"
    echo ""
    echo "-c    kickstart config file tied to this livecd."
    echo "-x    drop to the shell before quitting."
    echo "-d    cache dir; default is /var/tmp/litevirt-cache."
    echo "-l    product label; default is litevirt."

    exit
}

if [ ! -f /bin/livecd-creator ]; then
    echo "livecd-tools is missing; try \"yum install -y livecd-tools\" to install it."
    exit -1
fi 

if [ ! -f /bin/image-minimizer ]; then
    echo "appliance-tools-minimizer is missing; try \"yum install -y appliance-tools-minimizer\" to install it."
    exit -1
fi 

#default cache dir
CD=/var/tmp/litevirt-cache
[ -d $CD ] || mkdir -p $CD

#default drop-to-shell is disabled
SH=""

#default label
LB=litevirt

while getopts ":d:c:l:hx" opt; do
  case $opt in
    c)
      KS=$OPTARG
      ;;
    x)
      SH="--shell"
      ;;
    d)
      CD=$OPTARG
      ;;
    l)
      LB=$OPTARG
      ;;
    h)
      usage
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2  
      usage
      exit -1
      ;;
  esac
done

CMD="livecd-creator --cache=$CD --config=$KS --fslabel=$LB --title=$LB --product=$LB -d $SH"
echo $CMD
$CMD
